server:
  port: 8082

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: "jdbc:log4jdbc:oracle:thin:@localhost:1521:xe"
    username: kosa01
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kosa.Catchvegan.DTO