server:
  port: 8082

spring:
  messages:
    basename: message

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: "jdbc:log4jdbc:oracle:thin:@localhost:1521:xe"
    username: kosa01
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kosa.Catchvegan.DTO

logging:
  config: src/main/resources/log4j2.xml

quartz:
  properties:
    org:
      quartz:
        jobStore:
          class: org.quartz.impl.jdbcjobstore.JobStoreTX
          driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          dataSource: myDataSource
          tablePrefix: QRTZ_
        dataSource:
          myDataSource:
            driver: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
            URL: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
            user: kosa01
            password: 1234
        threadPool:
          threadCount: 3
twilio:
  account:
    sid: ACe7800a91efb2cbb3d1c9fc0e6d83c630
  auth:
    token: e46763b4c0c31ecf549e57643c3e7834
  from:
    number: +15074458078